### ISSUE TITLE
ArgumentCountError after install

### ISSUE THREAD

**Issue by hspf-feldberg** [a-r-m-i-n/mbox#1]
Hello Armin,

first of all, thank you for this helpful extension!

I am currently testing it on ddev and unfortunately encountered an issue directly after installing it and calling the backend of my TYPO3 to log into it.

![image](https://github.com/a-r-m-i-n/mbox/assets/64191248/fffdfa25-e5a3-46ca-bbc1-efdb6ff94aab)

So the problem occurs in **mbox\Configuration\Services.php**. I am not an expert here, but it seems that this only occurs when the extension is freshly installed on a previously mbox-extension-free TYPO3 installation. At least I was able to mitigate this problem by removing the lines 16-21 from the Services.php file when calling the backend and putting it back in after I successfully logged in to the backend. The original error did not reappear after that. As if it was dependent on some kind of first time initialisation of the freshly installed extension that I do not know about.

Greetings!

**Comment by a-r-m-i-n** [comment]
Hey. Those lines are registering a Symfony command conditionally, only when the debugMode in extension settings is enabled.

When you enable this mode, you also need to clear all caches from the install tool (or delete the var/cache/code directory).

**Comment by a-r-m-i-n** [comment]
Closed, because of no response.
