### ISSUE TITLE
Empty lines in mbox file affect parsing 

### ISSUE THREAD

**Issue by izzycole** [a-r-m-i-n/mbox#6]
For some reason, my mbox file has 2 linebreaks after each boundary, which causes MailMessages rendered empty.

I could hotfix it by trimming the messageLines in MailMessage.php:47

```php
fwrite($stream, implode('', $this->messageLines));
``` 
to
```php
fwrite($stream, trim(implode('', $this->messageLines)));
``` 

maybe that could be implemented generally.

thanks!
Sebi

<img width="574" alt="Bildschirmfoto 2024-02-20 um 12 00 49" src="https://github.com/a-r-m-i-n/mbox/assets/12833273/452c736a-aa5a-429b-9d05-74b77bfa4cd2">

<img width="740" alt="Bildschirmfoto 2024-02-20 um 12 02 25" src="https://github.com/a-r-m-i-n/mbox/assets/12833273/41072913-ec30-41f9-ae73-fbba72eb28a9">

<img width="1486" alt="Bildschirmfoto 2024-02-20 um 12 02 48" src="https://github.com/a-r-m-i-n/mbox/assets/12833273/505020f3-48d9-451b-bf64-8a811b1b0a9b">

**Comment by a-r-m-i-n** [comment]
Do you use the shipped `T3\Mbox\MboxTransport` in your mail configuration?

And it would be interesting to know the exact TYPO3, PHP and mbox extension version, you are using.

**Comment by izzycole** [comment]
yes i use the shipped class like this

```php
    $GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport'] = 'T3\Mbox\MboxTransport';
``` 

mbox 2.1.0

TYPO3 Version	11.5.33
Webserver	Apache
PHP Version	7.4.33
Database (Default)	MySQL 10.4.32-MariaDB
Application Context	Production/Staging
Operating System	Linux 3.10.0-1160.108.1.el7.x86_64

Is suspect that the 2 emtpy lines are added in MboxTransport.php:57

```php
$mboxEmail = $mboxFromLine . $emailAsString . PHP_EOL . PHP_EOL;
```

**Comment by a-r-m-i-n** [comment]
Two line breaks should cause one empty line, not two. For any reason, your mail message ends with a line break, which is not expected. And this causes the two empty lines.

I think instead of adjusting the parser as you suggested, `trim($emailAsString)` is an easier fix.
